# apiVersion: v1
# kind: Secret
# metadata:
#   name: gameserver-secret
#   namespace: newtopia-app
# type: Opaque
# stringData:
#   SPRING_PROFILES_ACTIVE: "prod"

#   # DB SECTIONS
#   POSTGRES_DATABASE: "DB_NAME"
#   POSTGRES_USER: "DB_USER"
#   POSTGRES_PASSWORD: "DB_PASSWORD"
#   POSTGRES_PORT: "5432"
#   POSTGRES_HOST: "postgres-service.newtopia-db.svc.cluster.local"

#   # Redis Sections
#   REDIS_HOST: "redis-service.newtopia-db.svc.cluster.local"
#   REDIS_PORT: "6379"

#   #Kafka Sections
#   KAFKA_BOOTSTRAP_SERVERS: "KAFKA_BOOTSTRAP_SERVERS"
#   KAFKA_CONSUMER_GROUP: "KAFKA_CONSUMER_GROUP"

#   MINIO_ENDPOINT: "MINIO_ENDPOINT"
#   MINIO_ACCESS_KEY: "MINIO_ACCESS_KEY"
#   MINIO_SECRET_KEY: "MINIO_SECRET_KEY"
#   MINIO_BUCKET_NAME: "MINIO_BUCKET_NAME"
#   MINIO_PUBLIC_BASE_URL: "MINIO_PUBLIC_BASE_URL"

#   JWT_SECRET: "JWT_SECRET"  

#   OPENAPI_SECRET_KEY: "OPENAPI_SECRET_KEY"