# apiVersion: v1
# kind: Secret
# metadata:
#   name: gitlab-runner-config-secret
#   namespace: gitlab-runner
# type: Opaque
# stringData:
#   config.toml: |
#     concurrent = 4
#     check_interval = 3
#     log_level = "info"
    
#     [[runners]]
#       name = "kubernetes-runner"
#       url = "GITLAB_URL"
#       token = "REGISTRATION_TOKEN"
#       executor = "kubernetes"
      
#       [runners.kubernetes]
#         host = ""
#         namespace = "gitlab-runner"
#         privileged = true
#         image = "alpine:latest"
#         [[runners.kubernetes.volumes.empty_dir]]
#           name = "tmp-volume"
#           mount_path = "/tmp"
#         [[runners.kubernetes.volumes.empty_dir]]
#           name = "builds-volume"
#           mount_path = "/builds"