# apiVersion: v1
# kind: Secret
# metadata:
#   name: minio-secret
#   namespace: newtopia-minio
#   labels:
#     app: newtopia-minio
#     component: minio
# type: Opaque
# stringData:
#   MINIO_ROOT_USER: "REPLACE_WITH_MINIO_USER"
#   MINIO_ROOT_PASSWORD: "REPLACE_WITH_MINIO_PASSWORD"