spring:
  application:
    name: gameserver

  profiles:
    active: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        "[default_batch_fetch_size]": 500
        "[highlight_sql]": true
