spring:
  application:
    name: gameserver

  profiles:
    active: local

  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create  # 각 profile의 yml 파일로 이동
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        "[default_batch_fetch_size]": 500
        "[highlight_sql]": true
    defer-datasource-initialization: true

# 시드 이미지 업로드 설정
app:
  seed:
    enabled: true
    npc:
      enabled: true
      overwrite: if_changed                     # never | if_changed | always
      location: classpath:seed/npc/*.*     # 또는 file:/opt/seed/npc/*.*
      match-by: code                       # code | id  (파일명 규칙과 맞추기: SLIME.png 또는 10.png)
      storage:
        domain: npc
    ending:
      enabled: true
      overwrite: if_changed
      location: classpath:seed/ending/*.*
      match-by: code
      storage:
        domain: ending


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
      base-path: /actuator    # 기본값
  endpoint:
    health:
      show-details: "when_authorized"

# JWT 설정
jwt:
  secret: "YXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGY="  # TODO: 실제 프로덕션에서는 환경변수로 관리
  access-token-expiration: 900000      # 15분 (15 * 60 * 1000)
  refresh-token-expiration: 604800000  # 7일 (7 * 24 * 60 * 60 * 1000)

# 쿠키 설정
cookie:
  secure: false
  same-site: "Lax"
  access-token-name: "accessToken"
  refresh-token-name: "refreshToken"