spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/newtopia
    username: newtopia
    password: newtopia
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
