apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app: newtopia-db
    component: redis
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.26.14.247
    path: "/nfs/redis-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: newtopia-db
  labels:
    app: newtopia-db
    component: redis
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: newtopia-db
      component: redis