apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: newtopia-minio
  labels:
    app: newtopia-minio
    component: minio
spec:
  serviceName: "minio-service"
  replicas: 1
  selector:
    matchLabels:
      app: newtopia-minio
  template:
    metadata:
      labels:
        app: newtopia-minio
        component: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        command:
        - /bin/bash
        - -c
        args:
        - minio server /data --console-address ":9001"
        volumeMounts:
          - name: minio-pv
            mountPath: /data
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        envFrom:
          - secretRef:
              name: minio-secret
      volumes:
      - name: minio-pv
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: newtopia-minio
  labels:
    app: newtopia-minio
    component: minio
spec:
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: newtopia-minio
    component: minio
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: newtopia-minio
  labels:
    app: newtopia-minio
    component: minio
spec:
  ports:
  - name: console
    port: 9001
    nodePort: 30901
    protocol: TCP
  selector:
    app: newtopia-minio
    component: minio
  type: NodePort