apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: newtopia-db
  labels:
    app: newtopia-db
    component: redis
spec:
  serviceName: "redis-service"
  replicas: 1 # by default is 1
  selector:
    matchLabels:
      app: newtopia-db # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: newtopia-db # has to match .spec.selector.matchLabels
        component: redis
    spec:
      nodeSelector:
        location: aws
      containers:
      - name: redis
        image: redis:7-alpine
        volumeMounts:
          - name:  redis-pv
            mountPath: /data
        ports:
        - containerPort: 6379
          name: redis
      volumes:
      - name: redis-pv
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: newtopia-db
  labels:
    app: newtopia-db
    component: redis
spec:
  type: ClusterIP
  selector:
    app: newtopia-db
    component: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis